name: "Update README.md"

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Run updater.py
        env:
          GAMERTAG: ${{ secrets.GAMERTAG }}
        run: |
          python updater.py

      - name: Commit and push if changed
        run: |
          git config user.name "Yuuka Chan"
          git config user.email "kiizuha@gnuweeb.org"
          git diff
          git add .
          git commit -sm "workflow: update some magic~"
          git push
